config/routes.rb
PdfSampleApp::Application.routes.draw do
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order("created_at DESC")
  end
  
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do
        pdf = PrinterFriendlyArticle.new(@article, view_context)
        send_data pdf.render, filename: "article_#{@article.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: 'Article was successfully updated.'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: 'Article was successfully deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :safe_links_only => true, :filter_html => true, :hard_wrap => true, :tables => true, :autolink => true)
    markdown.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title, :input_html => {:class => 'span9'} %>
  <%= f.input :author, :input_html => {:class => 'span9'}  %>
  <%= f.input :body, :input_html => {:class => 'span9'}  %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = @article.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<div class="page-header">
  <h1>Articles</h1>
</div>
    <% @articles.each do |article| %>
      <h2><%= link_to article.title, article_path(article) %></h2><br />
      <p><small>Posted by <%= article.author%></small></p>
      <p><%= markdown article.body %></p>
      <p>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_article_path(article), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    article_path(article),
                    :method => :delete,
                    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                    :class => 'btn btn-mini btn-danger' %>
      </p>
      <hr />
    <% end %>
<%= link_to "New Article",
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = @article.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div class="page-header">
  <h1><%= @article.title %></h1>
  <p><small>Posted by <%= @article.author %></small></p>
</div>
  <p><%= link_to "Printer Friendly Version", article_path(@article, format: "pdf"), :class => "btn btn-primary btn-mini" %></p>
  <p><%= markdown @article.body %></p>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PdfSampleApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">PdfSampleApp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Articles", articles_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>